import ObjectUtilities from "../utility/ObjectUtilities.js";

import MysteryAward from "../artifact/MysteryAward.js";

import Book from "./Book.js";
import Nomination from "./Nomination.js";
import UserSettings from "./UserSettings.js";

function MysteryInitialState()
{
   this.winnerImage = "../resource/image/BloodSplatter14.png";
   this.books = [];
   this.bookToDclUrl = {};
   this.bookToNomination = {};
   this.bookToAssessment = {};

   var agatha = MysteryAward.properties.agatha;
   var anthony = MysteryAward.properties.anthony;
   var barry = MysteryAward.properties.barry;
   var crimeAndBeyond = MysteryAward.properties.crimeAndBeyond;
   var dagger = MysteryAward.properties.dagger;
   var edgar = MysteryAward.properties.edgar;
   var shamus = MysteryAward.properties.shamus;

   this.books.push(new Book("Adrift", "Micki Browning"));
   this.books.push(new Book("The Ashes of Berlin", "Luke McCallin"));
   this.books.push(new Book("The Beautiful Dead", "Belinda Bauer"));
   this.books.push(new Book("Black Fall", "Andrew Mayne"));
   this.books.push(new Book("The Black Widow", "Daniel Silva"));
   this.books.push(new Book("Blessed Are the Peacemakers", "Kristi Belcamino"));
   this.books.push(new Book("Blood Wedding", "Pierre Lemaître"));
   this.books.push(new Book("Bluebird, Bluebird", "Attica Locke"));
   this.books.push(new Book("By Gaslight", "Steven Price"));
   this.books.push(new Book("A Cajun Christmas Killing", "Ellen Byron"));
   this.books.push(new Book("Called to Justice", "Edith Maxwell"));
   this.books.push(new Book("A Christmas Party", "Georgette Heyer"));
   this.books.push(new Book("The City in Darkness", "Michael Russell"));
   this.books.push(new Book("A Climate of Fear", "Fred Vargas"));
   this.books.push(new Book("A Cold Death (APA Adam’s Rib)", "Antonio Manzini"));
   this.books.push(new Book("The Constant Soldier", "William Ryan"));
   this.books.push(new Book("The Couple Next Door", "Shari Lapena"));
   this.books.push(new Book("Crime Scene", "Jonathan and Jesse Kellerman"));
   this.books.push(new Book("The Crossing", "Michael Connelly"));
   this.books.push(new Book("Dangerous To Know", "Renee Patrick"));
   this.books.push(new Book("Dark Chapter", "Winnie M. Li"));
   this.books.push(new Book("Daughters of Bad Men", "Laura Oles"));
   this.books.push(new Book("The Day I Died", "Lori Rader-Day"));
   this.books.push(new Book("Dead Man’s Blues", "Ray Celestin"));
   this.books.push(new Book("Death Overdue", "Allison Brook"));
   this.books.push(new Book("The Deep Dark Descending", "Allen Eskens"));
   this.books.push(new Book("Deep Six", "D.P. Lyle"));
   this.books.push(new Book("The Detective and the Chinese High-Fin", "Michael Craven"));
   this.books.push(new Book("The Devil’s Feast", "M.J. Carter"));
   this.books.push(new Book("The Dime", "Kathleen Kent"));
   this.books.push(new Book("Distress Signals", "Catherine Ryan Howard"));
   this.books.push(new Book("The Dry", "Jane Harper"));
   this.books.push(new Book("The Dying Detective", "Leif GW Persson"));
   this.books.push(new Book("The English Spy", "Daniel Silva"));
   this.books.push(new Book("Every Last Lie", "Mary Kubica"));
   this.books.push(new Book("Exit Strategy", "Steve Hamilton"));
   this.books.push(new Book("Fever City", "Tim Baker"));
   this.books.push(new Book("Fields Where They Lay", "Timothy Hallinan"));
   this.books.push(new Book("A Fine Line", "Gianrico Carofiglio"));
   this.books.push(new Book("Fool Me Once", "Harlan Coben"));
   this.books.push(new Book("The Force", "Don Winslow"));
   this.books.push(new Book("The Freedom Broker", "K.J. Howe"));
   this.books.push(new Book("The Girl in Green", "Derek B. Miller"));
   this.books.push(new Book("Glass Houses", "Louise Penny"));
   this.books.push(new Book("Good Me, Bad Me", "Ali Land"));
   this.books.push(new Book("The Graveyard of the Hesperides", "Lindsey Davis"));
   this.books.push(new Book("A Great Reckoning", "Louise Penny"));
   this.books.push(new Book("Gunmetal Gray", "Mark Greaney"));
   this.books.push(new Book("Heart of Stone", "James W. Ziskin"));
   this.books.push(new Book("Hellbent", "Gregg Hurwitz"));
   this.books.push(new Book("Hold Me, Babe", "O’Neil De Noux"));
   this.books.push(new Book("Hollywood Homicide", "Kellye Garrett"));
   this.books.push(new Book("Home", "Harlan Coben"));
   this.books.push(new Book("How To Kill Friends and Implicate People", "Jay Stringer"));
   this.books.push(new Book("I Know a Secret", "Tess Gerritsen"));
   this.books.push(new Book("I See You", "Clare Mackintosh"));
   this.books.push(new Book("IQ", "Joe Ide"));
   this.books.push(new Book("Idaho", "Emily Ruskovich"));
   this.books.push(new Book("In Farleigh Field", "Rhys Bowen"));
   this.books.push(new Book("In a Dark, Dark Wood", "Ruth Ware"));
   this.books.push(new Book("Ink and Bone", "Lisa Unger"));
   this.books.push(new Book("The Irregular", "H.B. Lyle"));
   this.books.push(new Book("The Killing Game", "J.S. Carol"));
   this.books.push(new Book("The Knife Slipped", "Erle Stanley Gardner"));
   this.books.push(new Book("The Last Painting of Sara de Vos", "Dominic Smith"));
   this.books.push(new Book("The Late Show", "Michael Connelly"));
   this.books.push(new Book("Leadfoot", "Eric Beetner"));
   this.books.push(new Book("The Legacy of the Bones", "Delores Redondo"));
   this.books.push(new Book("Lola", "Melissa Scrivner Love"));
   this.books.push(new Book("The Long Drop", "Denise Mina"));
   this.books.push(new Book("The Lost Ones", "Sheena Kamal"));
   this.books.push(new Book("Magpie Murders", "Anthony Horowitz"));
   this.books.push(new Book("Marked for Life", "Emelie Schepp"));
   this.books.push(new Book("The Marsh King’s Daughter", "Karen Dionne"));
   this.books.push(new Book("Murder in an English Village", "Jessica Ellicott"));
   this.books.push(new Book("My Absolute Darling", "Gabriel Tallent"));
   this.books.push(new Book("My Bad: A Mile High Noir", "Manuel Ramos"));
   this.books.push(new Book("No Way Home", "Annette Dashofy"));
   this.books.push(new Book("The Nowhere Man", "Gregg Hurwitz"));
   this.books.push(new Book("The Old Man", "Thomas Perry"));
   this.books.push(new Book("Orphan X", "Gregg Hurwitz"));
   this.books.push(new Book("The Paris Spy", "Susan Elia MacNeal"));
   this.books.push(new Book("Penance", "Kanae Minato"));
   this.books.push(new Book("The Perplexing Theft of the Jewel in the Crown", "Vaseem Khan"));
   this.books.push(new Book("The Pictures", "Guy Bolton"));
   this.books.push(new Book("The Plot is Murder", "V.M. Burns"));
   this.books.push(new Book("Protocol", "Kathleen Valenti"));
   this.books.push(new Book("Prussian Blue", "Philip Kerr"));
   this.books.push(new Book("Ragdoll", "Daniel Cole"));
   this.books.push(new Book("Ragged Lake", "Ron Corbett"));
   this.books.push(new Book("Rain Dogs", "Adrian McKinty"));
   this.books.push(new Book("Red Right Hand", "Chris Holm"));
   this.books.push(new Book("Redemption Road", "John Hart"));
   this.books.push(new Book("A Rising Man", "Abir Mukherjee"));
   this.books.push(new Book("The Rules of Backyard Cricket", "Jock Serong"));
   this.books.push(new Book("Safe from Harm", "R.J. Bailey"));
   this.books.push(new Book("Salem’s Cipher", "Jess Lourey"));
   this.books.push(new Book("The Second Girl", "David Swinson"));
   this.books.push(new Book("She Rides Shotgun", "Jordan Harpe r"));
   this.books.push(new Book("She Rides Shotgun", "Jordan Harper"));
   this.books.push(new Book("Shot in Detroit", "Patricia Abbott"));
   this.books.push(new Book("Sirens", "Joseph Knox"));
   this.books.push(new Book("SoHo Sins", "Richard Vine"));
   this.books.push(new Book("Spook Street", "Mick Herron"));
   this.books.push(new Book("The Stardom Affair", "Robert S. Levinson"));
   this.books.push(new Book("Super Con", "James Swain"));
   this.books.push(new Book("Take Out", "Margaret Maron"));
   this.books.push(new Book("Tall Oaks", "Chris Whitaker"));
   this.books.push(new Book("Tornado Weather", "Deborah E. Kennedy"));
   this.books.push(new Book("Trap the Devil", "Ben Coes"));
   this.books.push(new Book("The Travelers", "Chris Pavone"));
   this.books.push(new Book("The Twelve Lives of Samuel Hawley", "Hannah Tinti"));
   this.books.push(new Book("Two Kinds of Truth", "Michael Connelly"));
   this.books.push(new Book("UNSUB", "Meg Gardiner"));
   this.books.push(new Book("The Unseeing", "Anna Mazzola"));
   this.books.push(new Book("We Go Around in the Night and are Consumed by Fire", "Jules Grant"));
   this.books.push(new Book("Where It Hurts", "Reed Farrel Coleman"));
   this.books.push(new Book("Wilde Lake", "Laura Lippman"));
   this.books.push(new Book("With 6 You Get Wally", "Al Lamanda"));
   this.books.push(new Book("The Woman in Cabin 10", "Ruth Ware"));
   this.books.push(new Book("The Wrong Side of Goodbye", "Michael Connelly"));
   this.books.push(new Book("You Will Know Me", "Megan Abbott"));

   this.bookToDclUrl[this.books[2]] = "https://dcl.bibliocommons.com/item/show/1358030114";
   this.bookToDclUrl[this.books[3]] = "https://dcl.bibliocommons.com/item/show/1386509114";
   this.bookToDclUrl[this.books[4]] = "https://dcl.bibliocommons.com/item/show/1317748114";
   this.bookToDclUrl[this.books[6]] = "https://dcl.bibliocommons.com/item/show/1354388114";
   this.bookToDclUrl[this.books[7]] = "https://dcl.bibliocommons.com/item/show/1419940114";
   this.bookToDclUrl[this.books[8]] = "https://dcl.bibliocommons.com/item/show/1337265114";
   this.bookToDclUrl[this.books[9]] = "https://dcl.bibliocommons.com/item/show/1425601114";
   this.bookToDclUrl[this.books[10]] = "https://dcl.bibliocommons.com/item/show/1388567114";
   this.bookToDclUrl[this.books[12]] = "https://dcl.bibliocommons.com/item/show/1157596114";
   this.bookToDclUrl[this.books[13]] = "https://dcl.bibliocommons.com/item/show/1373923114";
   this.bookToDclUrl[this.books[16]] = "https://dcl.bibliocommons.com/item/show/1348740114";
   this.bookToDclUrl[this.books[17]] = "https://dcl.bibliocommons.com/item/show/1407385114";
   this.bookToDclUrl[this.books[18]] = "https://dcl.bibliocommons.com/item/show/1277014114";
   this.bookToDclUrl[this.books[19]] = "https://dcl.bibliocommons.com/item/show/1401420114";
   this.bookToDclUrl[this.books[20]] = "https://dcl.bibliocommons.com/item/show/1427070114";
   this.bookToDclUrl[this.books[22]] = "https://dcl.bibliocommons.com/item/show/1374142114";
   this.bookToDclUrl[this.books[23]] = "https://dcl.bibliocommons.com/item/show/1434826114";
   this.bookToDclUrl[this.books[24]] = "https://dcl.bibliocommons.com/item/show/1445899114";
   this.bookToDclUrl[this.books[25]] = "https://dcl.bibliocommons.com/item/show/1429038114";
   this.bookToDclUrl[this.books[26]] = "https://dcl.bibliocommons.com/item/show/1349982114";
   this.bookToDclUrl[this.books[27]] = "https://dcl.bibliocommons.com/item/show/1336378114";
   this.bookToDclUrl[this.books[29]] = "https://dcl.bibliocommons.com/item/show/1380018114";
   this.bookToDclUrl[this.books[30]] = "https://dcl.bibliocommons.com/item/show/1384331114";
   this.bookToDclUrl[this.books[31]] = "https://dcl.bibliocommons.com/item/show/1364617114";
   this.bookToDclUrl[this.books[32]] = "https://dcl.bibliocommons.com/item/show/1405432114";
   this.bookToDclUrl[this.books[33]] = "https://dcl.bibliocommons.com/item/show/1402218114";
   this.bookToDclUrl[this.books[34]] = "https://dcl.bibliocommons.com/item/show/1387222114";
   this.bookToDclUrl[this.books[35]] = "https://dcl.bibliocommons.com/item/show/1386156114";
   this.bookToDclUrl[this.books[36]] = "https://dcl.bibliocommons.com/item/show/1355235114";
   this.bookToDclUrl[this.books[39]] = "https://dcl.bibliocommons.com/item/show/1300151114";
   this.bookToDclUrl[this.books[40]] = "https://dcl.bibliocommons.com/item/show/1386414114";
   this.bookToDclUrl[this.books[41]] = "https://dcl.bibliocommons.com/item/show/1373831114";
   this.bookToDclUrl[this.books[42]] = "https://dcl.bibliocommons.com/item/show/1364905114";
   this.bookToDclUrl[this.books[43]] = "https://dcl.bibliocommons.com/item/show/1412170114";
   this.bookToDclUrl[this.books[44]] = "https://dcl.bibliocommons.com/item/show/1403968114";
   this.bookToDclUrl[this.books[45]] = "https://dcl.bibliocommons.com/item/show/1350030114";
   this.bookToDclUrl[this.books[46]] = "https://dcl.bibliocommons.com/item/show/1338084114";
   this.bookToDclUrl[this.books[47]] = "https://dcl.bibliocommons.com/item/show/1384335114";
   this.bookToDclUrl[this.books[48]] = "https://dcl.bibliocommons.com/item/show/1330252114";
   this.bookToDclUrl[this.books[49]] = "https://dcl.bibliocommons.com/item/show/1431233114";
   this.bookToDclUrl[this.books[51]] = "https://dcl.bibliocommons.com/item/show/1416206114";
   this.bookToDclUrl[this.books[52]] = "https://dcl.bibliocommons.com/item/show/1330605114";
   this.bookToDclUrl[this.books[54]] = "https://dcl.bibliocommons.com/item/show/1407387114";
   this.bookToDclUrl[this.books[55]] = "https://dcl.bibliocommons.com/item/show/1384268114";
   this.bookToDclUrl[this.books[56]] = "https://dcl.bibliocommons.com/item/show/1337552114";
   this.bookToDclUrl[this.books[57]] = "https://dcl.bibliocommons.com/item/show/1380270114";
   this.bookToDclUrl[this.books[58]] = "https://dcl.bibliocommons.com/item/show/1382653114";
   this.bookToDclUrl[this.books[59]] = "https://dcl.bibliocommons.com/item/show/1278756114";
   this.bookToDclUrl[this.books[60]] = "https://dcl.bibliocommons.com/item/show/1329715114";
   this.bookToDclUrl[this.books[61]] = "https://dcl.bibliocommons.com/item/show/1433441114";
   this.bookToDclUrl[this.books[63]] = "https://dcl.bibliocommons.com/item/show/1382373114";
   this.bookToDclUrl[this.books[64]] = "https://dcl.bibliocommons.com/item/show/1305320114";
   this.bookToDclUrl[this.books[65]] = "https://dcl.bibliocommons.com/item/show/1402219114";
   this.bookToDclUrl[this.books[68]] = "https://dcl.bibliocommons.com/item/show/1367618114";
   this.bookToDclUrl[this.books[69]] = "https://dcl.bibliocommons.com/item/show/1317755114";
   this.bookToDclUrl[this.books[70]] = "https://dcl.bibliocommons.com/item/show/1400194114";
   this.bookToDclUrl[this.books[71]] = "https://dcl.bibliocommons.com/item/show/1387233114";
   this.bookToDclUrl[this.books[72]] = "https://dcl.bibliocommons.com/item/show/1329705114";
   this.bookToDclUrl[this.books[73]] = "https://dcl.bibliocommons.com/item/show/1388785114";
   this.bookToDclUrl[this.books[74]] = "https://dcl.bibliocommons.com/item/show/1430980114";
   this.bookToDclUrl[this.books[75]] = "https://dcl.bibliocommons.com/item/show/1415034114";
   this.bookToDclUrl[this.books[76]] = "https://dcl.bibliocommons.com/item/show/1368257114";
   this.bookToDclUrl[this.books[78]] = "https://dcl.bibliocommons.com/item/show/1364629114";
   this.bookToDclUrl[this.books[79]] = "https://dcl.bibliocommons.com/item/show/1364630114";
   this.bookToDclUrl[this.books[80]] = "https://dcl.bibliocommons.com/item/show/1431233114";
   this.bookToDclUrl[this.books[81]] = "https://dcl.bibliocommons.com/item/show/1418398114";
   this.bookToDclUrl[this.books[82]] = "https://dcl.bibliocommons.com/item/show/1400217114";
   this.bookToDclUrl[this.books[83]] = "https://dcl.bibliocommons.com/item/show/1354402114";
   this.bookToDclUrl[this.books[84]] = "https://dcl.bibliocommons.com/item/show/1421309114";
   this.bookToDclUrl[this.books[85]] = "https://dcl.bibliocommons.com/item/show/1440192114";
   this.bookToDclUrl[this.books[87]] = "https://dcl.bibliocommons.com/item/show/1388038114";
   this.bookToDclUrl[this.books[88]] = "https://dcl.bibliocommons.com/item/show/1365869114";
   this.bookToDclUrl[this.books[90]] = "https://dcl.bibliocommons.com/item/show/1313210114";
   this.bookToDclUrl[this.books[91]] = "https://dcl.bibliocommons.com/item/show/1330925114";
   this.bookToDclUrl[this.books[92]] = "https://dcl.bibliocommons.com/item/show/1316552114";
   this.bookToDclUrl[this.books[93]] = "https://dcl.bibliocommons.com/item/show/1401861114";
   this.bookToDclUrl[this.books[94]] = "https://dcl.bibliocommons.com/item/show/1415342114";
   this.bookToDclUrl[this.books[96]] = "https://dcl.bibliocommons.com/item/show/1351405114";
   this.bookToDclUrl[this.books[97]] = "https://dcl.bibliocommons.com/item/show/1313211114";
   this.bookToDclUrl[this.books[99]] = "https://dcl.bibliocommons.com/item/show/1407263114";
   this.bookToDclUrl[this.books[100]] = "https://dcl.bibliocommons.com/item/show/1349998114";
   this.bookToDclUrl[this.books[101]] = "https://dcl.bibliocommons.com/item/show/1445854114";
   this.bookToDclUrl[this.books[103]] = "https://dcl.bibliocommons.com/item/show/1366970114";
   this.bookToDclUrl[this.books[106]] = "https://dcl.bibliocommons.com/item/show/1388587114";
   this.bookToDclUrl[this.books[108]] = "https://dcl.bibliocommons.com/item/show/1410081114";
   this.bookToDclUrl[this.books[109]] = "https://dcl.bibliocommons.com/item/show/1402225114";
   this.bookToDclUrl[this.books[110]] = "https://dcl.bibliocommons.com/item/show/1300055114";
   this.bookToDclUrl[this.books[111]] = "https://dcl.bibliocommons.com/item/show/1366837114";
   this.bookToDclUrl[this.books[112]] = "https://dcl.bibliocommons.com/item/show/1412693114";
   this.bookToDclUrl[this.books[113]] = "https://dcl.bibliocommons.com/item/show/1431236114";
   this.bookToDclUrl[this.books[114]] = "https://dcl.bibliocommons.com/item/show/1381431114";
   this.bookToDclUrl[this.books[116]] = "https://dcl.bibliocommons.com/item/show/1297412114";
   this.bookToDclUrl[this.books[117]] = "https://dcl.bibliocommons.com/item/show/1306939114";
   this.bookToDclUrl[this.books[118]] = "https://dcl.bibliocommons.com/item/show/1363135114";
   this.bookToDclUrl[this.books[119]] = "https://dcl.bibliocommons.com/item/show/1317758114";
   this.bookToDclUrl[this.books[120]] = "https://dcl.bibliocommons.com/item/show/1337567114";
   this.bookToDclUrl[this.books[121]] = "https://dcl.bibliocommons.com/item/show/1317759114";

   this.initializeBookToNomination();

   this.bookToNomination[this.books[0]].push(new Nomination(agatha, agatha.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[1]].push(new Nomination(dagger, dagger.categories.properties.historical, 2017, false));
   this.bookToNomination[this.books[2]].push(new Nomination(dagger, dagger.categories.properties.gold, 2017, false));
   this.bookToNomination[this.books[3]].push(new Nomination(edgar, edgar.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[4]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[5]].push(new Nomination(barry, barry.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[6]].push(new Nomination(dagger, dagger.categories.properties.international, 2017, false));
   this.bookToNomination[this.books[7]].push(new Nomination(edgar, edgar.categories.properties.novel, 2018, true));
   this.bookToNomination[this.books[8]].push(new Nomination(dagger, dagger.categories.properties.historical, 2017, false));
   this.bookToNomination[this.books[9]].push(new Nomination(agatha, agatha.categories.properties.contemporary, 2017, false));
   this.bookToNomination[this.books[10]].push(new Nomination(agatha, agatha.categories.properties.historical, 2017, false));
   this.bookToNomination[this.books[11]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[12]].push(new Nomination(dagger, dagger.categories.properties.historical, 2017, false));
   this.bookToNomination[this.books[13]].push(new Nomination(dagger, dagger.categories.properties.international, 2017, false));
   this.bookToNomination[this.books[14]].push(new Nomination(dagger, dagger.categories.properties.international, 2017, false));
   this.bookToNomination[this.books[15]].push(new Nomination(dagger, dagger.categories.properties.steel, 2017, false));
   this.bookToNomination[this.books[16]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2018, false));
   this.bookToNomination[this.books[17]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2018, false));
   this.bookToNomination[this.books[18]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2016, false));
   this.bookToNomination[this.books[19]].push(new Nomination(agatha, agatha.categories.properties.historical, 2017, false));
   this.bookToNomination[this.books[20]].push(new Nomination(edgar, edgar.categories.properties.first, 2018, false));
   this.bookToNomination[this.books[21]].push(new Nomination(agatha, agatha.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[22]].push(new Nomination(barry, barry.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[23]].push(new Nomination(dagger, dagger.categories.properties.gold, 2017, false));
   this.bookToNomination[this.books[24]].push(new Nomination(agatha, agatha.categories.properties.contemporary, 2017, false));
   this.bookToNomination[this.books[25]].push(new Nomination(barry, barry.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[26]].push(new Nomination(shamus, shamus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[27]].push(new Nomination(shamus, shamus.categories.properties.paperback, 2017, false));
   this.bookToNomination[this.books[28]].push(new Nomination(dagger, dagger.categories.properties.historical, 2017, false));
   this.bookToNomination[this.books[29]].push(new Nomination(edgar, edgar.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[30]].push(new Nomination(dagger, dagger.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[31]].push(new Nomination(dagger, dagger.categories.properties.gold, 2017, true));
   this.bookToNomination[this.books[31]].push(new Nomination(barry, barry.categories.properties.first, 2018, false));
   this.bookToNomination[this.books[32]].push(new Nomination(dagger, dagger.categories.properties.international, 2017, true));
   this.bookToNomination[this.books[33]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[34]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2018, false));
   this.bookToNomination[this.books[35]].push(new Nomination(barry, barry.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[36]].push(new Nomination(shamus, shamus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[37]].push(new Nomination(shamus, shamus.categories.properties.hardcover, 2017, false));
   this.bookToNomination[this.books[38]].push(new Nomination(dagger, dagger.categories.properties.international, 2017, false));
   this.bookToNomination[this.books[39]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[40]].push(new Nomination(barry, barry.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[41]].push(new Nomination(barry, barry.categories.properties.thriller, 2018, false));
   this.bookToNomination[this.books[42]].push(new Nomination(dagger, dagger.categories.properties.gold, 2017, false));
   this.bookToNomination[this.books[43]].push(new Nomination(agatha, agatha.categories.properties.contemporary, 2017, true));
   this.bookToNomination[this.books[44]].push(new Nomination(dagger, dagger.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[45]].push(new Nomination(shamus, shamus.categories.properties.hardcover, 2017, false));
   this.bookToNomination[this.books[46]].push(new Nomination(anthony, anthony.categories.properties.mystery, 2017, true));
   this.bookToNomination[this.books[47]].push(new Nomination(barry, barry.categories.properties.thriller, 2018, false));
   this.bookToNomination[this.books[48]].push(new Nomination(anthony, anthony.categories.properties.paperback, 2017, true));
   this.bookToNomination[this.books[49]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2018, false));
   this.bookToNomination[this.books[50]].push(new Nomination(shamus, shamus.categories.properties.paperback, 2017, false));
   this.bookToNomination[this.books[51]].push(new Nomination(agatha, agatha.categories.properties.first, 2017, true));
   this.bookToNomination[this.books[51]].push(new Nomination(barry, barry.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[52]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[53]].push(new Nomination(anthony, anthony.categories.properties.paperback, 2017, false));
   this.bookToNomination[this.books[54]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2018, false));
   this.bookToNomination[this.books[55]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2018, false));
   this.bookToNomination[this.books[56]].push(new Nomination(shamus, shamus.categories.properties.first, 2017, true));
   this.bookToNomination[this.books[57]].push(new Nomination(edgar, edgar.categories.properties.first, 2018, false));
   this.bookToNomination[this.books[58]].push(new Nomination(agatha, agatha.categories.properties.historical, 2017, true));
   this.bookToNomination[this.books[58]].push(new Nomination(edgar, edgar.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[59]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[60]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2016, false));
   this.bookToNomination[this.books[61]].push(new Nomination(barry, barry.categories.properties.first, 2018, false));
   this.bookToNomination[this.books[62]].push(new Nomination(dagger, dagger.categories.properties.steel, 2017, false));
   this.bookToNomination[this.books[63]].push(new Nomination(shamus, shamus.categories.properties.paperback, 2017, false));
   this.bookToNomination[this.books[64]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[65]].push(new Nomination(barry, barry.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[65]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2018, false));
   this.bookToNomination[this.books[66]].push(new Nomination(anthony, anthony.categories.properties.paperback, 2017, false));
   this.bookToNomination[this.books[67]].push(new Nomination(dagger, dagger.categories.properties.international, 2017, false));
   this.bookToNomination[this.books[68]].push(new Nomination(edgar, edgar.categories.properties.first, 2018, false));
   this.bookToNomination[this.books[69]].push(new Nomination(dagger, dagger.categories.properties.historical, 2017, false));
   this.bookToNomination[this.books[70]].push(new Nomination(barry, barry.categories.properties.first, 2018, false));
   this.bookToNomination[this.books[71]].push(new Nomination(barry, barry.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[72]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[73]].push(new Nomination(barry, barry.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[74]].push(new Nomination(agatha, agatha.categories.properties.historical, 2017, false));
   this.bookToNomination[this.books[75]].push(new Nomination(barry, barry.categories.properties.first, 2018, false));
   this.bookToNomination[this.books[76]].push(new Nomination(shamus, shamus.categories.properties.paperback, 2017, false));
   this.bookToNomination[this.books[77]].push(new Nomination(agatha, agatha.categories.properties.contemporary, 2017, false));
   this.bookToNomination[this.books[78]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[79]].push(new Nomination(barry, barry.categories.properties.thriller, 2018, false));
   this.bookToNomination[this.books[80]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[81]].push(new Nomination(agatha, agatha.categories.properties.historical, 2017, false));
   this.bookToNomination[this.books[82]].push(new Nomination(edgar, edgar.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[83]].push(new Nomination(shamus, shamus.categories.properties.paperback, 2017, true));
   this.bookToNomination[this.books[84]].push(new Nomination(dagger, dagger.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[85]].push(new Nomination(agatha, agatha.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[86]].push(new Nomination(agatha, agatha.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[87]].push(new Nomination(barry, barry.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[87]].push(new Nomination(edgar, edgar.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[88]].push(new Nomination(dagger, dagger.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[89]].push(new Nomination(edgar, edgar.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[90]].push(new Nomination(anthony, anthony.categories.properties.paperback, 2017, false));
   this.bookToNomination[this.books[91]].push(new Nomination(anthony, anthony.categories.properties.mystery, 2017, false));
   this.bookToNomination[this.books[92]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2016, false));
   this.bookToNomination[this.books[92]].push(new Nomination(dagger, dagger.categories.properties.steel, 2017, false));
   this.bookToNomination[this.books[93]].push(new Nomination(dagger, dagger.categories.properties.gold, 2017, false));
   this.bookToNomination[this.books[93]].push(new Nomination(dagger, dagger.categories.properties.historical, 2017, true));
   this.bookToNomination[this.books[93]].push(new Nomination(barry, barry.categories.properties.first, 2018, false));
   this.bookToNomination[this.books[93]].push(new Nomination(edgar, edgar.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[94]].push(new Nomination(edgar, edgar.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[95]].push(new Nomination(barry, barry.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[96]].push(new Nomination(anthony, anthony.categories.properties.paperback, 2017, false));
   this.bookToNomination[this.books[97]].push(new Nomination(shamus, shamus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[98]].push(new Nomination(barry, barry.categories.properties.first, 2018, false));
   this.bookToNomination[this.books[99]].push(new Nomination(edgar, edgar.categories.properties.first, 2018, true));
   this.bookToNomination[this.books[100]].push(new Nomination(anthony, anthony.categories.properties.paperback, 2017, false));
   this.bookToNomination[this.books[101]].push(new Nomination(dagger, dagger.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[102]].push(new Nomination(shamus, shamus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[103]].push(new Nomination(dagger, dagger.categories.properties.gold, 2017, false));
   this.bookToNomination[this.books[103]].push(new Nomination(dagger, dagger.categories.properties.steel, 2017, true));
   this.bookToNomination[this.books[103]].push(new Nomination(barry, barry.categories.properties.thriller, 2018, false));
   this.bookToNomination[this.books[104]].push(new Nomination(shamus, shamus.categories.properties.hardcover, 2017, false));
   this.bookToNomination[this.books[105]].push(new Nomination(barry, barry.categories.properties.paperback, 2018, false));
   this.bookToNomination[this.books[106]].push(new Nomination(agatha, agatha.categories.properties.contemporary, 2017, false));
   this.bookToNomination[this.books[107]].push(new Nomination(dagger, dagger.categories.properties.first, 2017, true));
   this.bookToNomination[this.books[108]].push(new Nomination(edgar, edgar.categories.properties.first, 2018, false));
   this.bookToNomination[this.books[109]].push(new Nomination(barry, barry.categories.properties.thriller, 2018, false));
   this.bookToNomination[this.books[110]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2016, false));
   this.bookToNomination[this.books[111]].push(new Nomination(edgar, edgar.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[112]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2018, false));
   this.bookToNomination[this.books[113]].push(new Nomination(barry, barry.categories.properties.thriller, 2018, false));
   this.bookToNomination[this.books[114]].push(new Nomination(edgar, edgar.categories.properties.paperback, 2018, true));
   this.bookToNomination[this.books[115]].push(new Nomination(dagger, dagger.categories.properties.steel, 2017, false));
   this.bookToNomination[this.books[116]].push(new Nomination(anthony, anthony.categories.properties.mystery, 2017, false));
   this.bookToNomination[this.books[116]].push(new Nomination(shamus, shamus.categories.properties.hardcover, 2017, true));
   this.bookToNomination[this.books[117]].push(new Nomination(anthony, anthony.categories.properties.mystery, 2017, false));
   this.bookToNomination[this.books[118]].push(new Nomination(shamus, shamus.categories.properties.hardcover, 2017, false));
   this.bookToNomination[this.books[119]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[120]].push(new Nomination(crimeAndBeyond, crimeAndBeyond.categories.properties.case, 2017, false));
   this.bookToNomination[this.books[121]].push(new Nomination(anthony, anthony.categories.properties.mystery, 2017, false));
   this.bookToNomination[this.books[121]].push(new Nomination(dagger, dagger.categories.properties.steel, 2017, false));

   this.initializeBookToAssessment();
   this.loadBookToAssessment();
}

MysteryInitialState.prototype.initializeBookToAssessment = function()
{
   this.bookToAssessment = UserSettings.resetBookToAssessment(this.bookToAssessment, this.books, this.bookToDclUrl, this.bookToNomination);
};

MysteryInitialState.prototype.initializeBookToNomination = function()
{
   this.books.forEach(function(book)
   {
      this.bookToNomination[book] = [];
   }, this);
};

MysteryInitialState.prototype.loadBookToAssessment = function()
{
   var myBookToAssessment = UserSettings.loadBookToAssessment();
   ObjectUtilities.merge(this.bookToAssessment, myBookToAssessment);
};

if (Object.freeze)
{
   Object.freeze(MysteryInitialState);
}

export default MysteryInitialState;