import ObjectUtilities from "../utility/ObjectUtilities.js";

import SciFiAward from "../artifact/SciFiAward.js";

import Book from "./Book.js";
import Nomination from "./Nomination.js";
import UserSettings from "./UserSettings.js";

function SciFiInitialState()
{
   this.winnerImage = "../resource/image/Rocketship14.png";
   this.books = [];
   this.bookToDclUrl = {};
   this.bookToNomination = {};
   this.bookToAssessment = {};

   var britishFantasy = SciFiAward.properties.britishFantasy;
   var britishSf = SciFiAward.properties.britishSf;
   var hugo = SciFiAward.properties.hugo;
   var locus = SciFiAward.properties.locus;
   var nebula = SciFiAward.properties.nebula;

   this.books.push(new Book("13 Minutes", "Sarah Pinborough"));
   this.books.push(new Book("The Aeronaut's Windlass", "Jim Butcher"));
   this.books.push(new Book("After Atlas", "Emma Newman"));
   this.books.push(new Book("All the Birds in the Sky", "Charlie Jane Anders"));
   this.books.push(new Book("Amberlough", "Lara Elena Donnelly"));
   this.books.push(new Book("Ancillary Mercy", "Ann Leckie"));
   this.books.push(new Book("Arabella of Mars", "David D. Levine"));
   this.books.push(new Book("Aurora", "Kim Stanley Robinson"));
   this.books.push(new Book("Autonomous", "Annalee Newitz"));
   this.books.push(new Book("Azanian Bridges", "Nick Wood"));
   this.books.push(new Book("Babylon's Ashes", "James S. A. Corey"));
   this.books.push(new Book("Barsk: The Elephants' Graveyard", "Lawrence M. Schoen"));
   this.books.push(new Book("Borderline", "Mishell Baker"));
   this.books.push(new Book("A Borrowed Man", "Gene Wolfe"));
   this.books.push(new Book("Central Station", "Lavie Tidhar"));
   this.books.push(new Book("Children of Earth and Sky", "Guy Gavriel Kay"));
   this.books.push(new Book("City of Blades", "Robert Jackson Bennett"));
   this.books.push(new Book("A Closed and Common Orbit", "Becky Chambers"));
   this.books.push(new Book("A Cold Silence", "Alison Littlewood"));
   this.books.push(new Book("The Collapsing Empire", "John Scalzi"));
   this.books.push(new Book("Company Town", "Madeline Ashby"));
   this.books.push(new Book("Daughter of Eden", "Chris Beckett"));
   this.books.push(new Book("The Death House", "Sarah Pinborough"));
   this.books.push(new Book("Death's End", "Cixin Liu"));
   this.books.push(new Book("Death's End", "Cixin Liu , translated by Ken Liu"));
   this.books.push(new Book("Disappearance at Devil's Rock", "Paul Tremblay"));
   this.books.push(new Book("Dreams Before the Start of Time", "Anne Charnock"));
   this.books.push(new Book("Europe at Midnight", "Dave Hutchinson"));
   this.books.push(new Book("Europe in Winter", "Dave Hutchinson"));
   this.books.push(new Book("Everfair", "Nisi Shawl"));
   this.books.push(new Book("Exit West", "Mohsin Hamid"));
   this.books.push(new Book("The Fifth Season", "N. K. Jemisin"));
   this.books.push(new Book("The Girl from Everywhere", "Heidi Heilig"));
   this.books.push(new Book("Glorious Angels", "Justina Robson"));
   this.books.push(new Book("The Grace of Kings", "Ken Liu"));
   this.books.push(new Book("Guns of the Dawn", "Adrian Tchaikovsky"));
   this.books.push(new Book("Half a War", "Joe Abercrombie"));
   this.books.push(new Book("The Hidden People", "Alison Littlewood"));
   this.books.push(new Book("The High King's Vengeance", "Steven Poore"));
   this.books.push(new Book("The House of Shattered Wings", "Aliette de Bodard"));
   this.books.push(new Book("Infomocracy", "Malka Older"));
   this.books.push(new Book("The Iron Ghost", "Jen Williams"));
   this.books.push(new Book("Jade City", "Fonda Lee"));
   this.books.push(new Book("Karen Memory", "Elizabeth Bear"));
   this.books.push(new Book("The Last Days of New Paris", "China Miéville"));
   this.books.push(new Book("Last Year", "Robert Charles Wilson"));
   this.books.push(new Book("Lost Girl", "Adam Nevill"));
   this.books.push(new Book("Luna: New Moon", "Ian McDonald"));
   this.books.push(new Book("The Medusa Chronicles", "Stephen Baxter & Alastair Reynolds"));
   this.books.push(new Book("Mother of Eden", "Chris Beckett"));
   this.books.push(new Book("Necessity", "Jo Walton"));
   this.books.push(new Book("New York 2140", "Kim Stanley Robinson"));
   this.books.push(new Book("The Nightmare Stacks", "Charles Stross"));
   this.books.push(new Book("Ninefox Gambit", "Yoon Ha Lee"));
   this.books.push(new Book("The Obelisk Gate", "N. K. Jemisin"));
   this.books.push(new Book("Occupy Me", "Tricia Sullivan"));
   this.books.push(new Book("Provenance", "Ann Leckie"));
   this.books.push(new Book("Raising Caine", "Charles E. Gannon"));
   this.books.push(new Book("Raven Stratagem", "Yoon Ha Lee"));
   this.books.push(new Book("Rawblood", "Catriona Ward"));
   this.books.push(new Book("The Reader", "Traci Chee"));
   this.books.push(new Book("The Rift", "Nina Allan"));
   this.books.push(new Book("Roses and Rot", "Kat Howard"));
   this.books.push(new Book("The Searching Dead", "Ramsey Campbell"));
   this.books.push(new Book("Seveneves", "Neal Stephenson"));
   this.books.push(new Book("Signal to Noise", "Silvia Moreno-Garcia"));
   this.books.push(new Book("The Silence", "Tim Lebbon"));
   this.books.push(new Book("The Silver Tide", "Jen Williams"));
   this.books.push(new Book("Six Wakes", "Mur Lafferty"));
   this.books.push(new Book("The Sorcerer of the Wildeeps", "Kai Ashante Wilson"));
   this.books.push(new Book("Sorcerer to the Crown", "Zen Cho"));
   this.books.push(new Book("Spoonbenders", "Daryl Gregory"));
   this.books.push(new Book("The Star-Touched Queen", "Roshani Chokshi"));
   this.books.push(new Book("The Stone Sky", "N. K. Jemisin"));
   this.books.push(new Book("The Strange Case of the Alchemist's Daughter", "Theodora Goss"));
   this.books.push(new Book("The Summer Goddess", "Joanne Hall"));
   this.books.push(new Book("Summerlong", "Peter S. Beagle"));
   this.books.push(new Book("Take Back the Sky", "Greg Bear"));
   this.books.push(new Book("The Tiger and the Wolf", "Adrian Tchaikovsky"));
   this.books.push(new Book("Too Like the Lightning", "Ada Palmer"));
   this.books.push(new Book("The Underground Railroad", "Colson Whitehead"));
   this.books.push(new Book("Updraft", "Fran Wilde"));
   this.books.push(new Book("Uprooted", "Naomi Novik"));
   this.books.push(new Book("Vigil", "Angela Slatter"));
   this.books.push(new Book("Visitor", "C. J. Cherryh"));
   this.books.push(new Book("The Wall of Storms", "Ken Liu"));
   this.books.push(new Book("The Watchmaker of Filigree Street", "Natasha Pulley"));
   this.books.push(new Book("The Water Knife", "Paolo Bacigalupi"));
   this.books.push(new Book("Waypoint Kangaroo", "Curtis Chen"));
   this.books.push(new Book("Welcome to Night Vale", "Joseph Fink & Jeffrey Cranor"));
   this.books.push(new Book("The Winged Histories", "Sofia Samatar"));
   this.books.push(new Book("Wylding Hall", "Elizabeth Hand"));

   this.bookToDclUrl[this.books[0]] = "https://dcl.bibliocommons.com/item/show/1430751114";
   this.bookToDclUrl[this.books[1]] = "https://dcl.bibliocommons.com/item/show/1283248114";
   this.bookToDclUrl[this.books[2]] = "https://dcl.bibliocommons.com/item/show/1367380114";
   this.bookToDclUrl[this.books[3]] = "https://dcl.bibliocommons.com/item/show/1306204114";
   this.bookToDclUrl[this.books[4]] = "https://dcl.bibliocommons.com/item/show/1468611114";
   this.bookToDclUrl[this.books[5]] = "https://dcl.bibliocommons.com/item/show/1407440114";
   this.bookToDclUrl[this.books[6]] = "https://dcl.bibliocommons.com/item/show/1466850114";
   this.bookToDclUrl[this.books[7]] = "https://dcl.bibliocommons.com/item/show/1275871114";
   this.bookToDclUrl[this.books[8]] = "https://dcl.bibliocommons.com/item/show/1423696114";
   this.bookToDclUrl[this.books[10]] = "https://dcl.bibliocommons.com/item/show/1381450114";
   this.bookToDclUrl[this.books[11]] = "https://dcl.bibliocommons.com/item/show/1407440114";
   this.bookToDclUrl[this.books[12]] = "https://dcl.bibliocommons.com/item/show/1313297114";
   this.bookToDclUrl[this.books[13]] = "https://dcl.bibliocommons.com/item/show/1293191114";
   this.bookToDclUrl[this.books[14]] = "https://dcl.bibliocommons.com/item/show/1317803114";
   this.bookToDclUrl[this.books[15]] = "https://dcl.bibliocommons.com/item/show/1322289114";
   this.bookToDclUrl[this.books[16]] = "https://dcl.bibliocommons.com/item/show/1305744114";
   this.bookToDclUrl[this.books[17]] = "https://dcl.bibliocommons.com/item/show/1388021114";
   this.bookToDclUrl[this.books[19]] = "https://dcl.bibliocommons.com/item/show/1373825114";
   this.bookToDclUrl[this.books[20]] = "https://dcl.bibliocommons.com/item/show/1322561114";
   this.bookToDclUrl[this.books[21]] = "https://dcl.bibliocommons.com/item/show/1445921114";
   this.bookToDclUrl[this.books[22]] = "https://dcl.bibliocommons.com/item/show/988188114";
   this.bookToDclUrl[this.books[23]] = "https://dcl.bibliocommons.com/item/show/1357571114";
   this.bookToDclUrl[this.books[24]] = "https://dcl.bibliocommons.com/item/show/1357571114";
   this.bookToDclUrl[this.books[25]] = "https://dcl.bibliocommons.com/item/show/1316729114";
   this.bookToDclUrl[this.books[29]] = "https://dcl.bibliocommons.com/item/show/1357853114";
   this.bookToDclUrl[this.books[30]] = "https://dcl.bibliocommons.com/item/show/1372783114";
   this.bookToDclUrl[this.books[31]] = "https://dcl.bibliocommons.com/item/show/1407440114";
   this.bookToDclUrl[this.books[32]] = "https://dcl.bibliocommons.com/item/show/1309572114";
   this.bookToDclUrl[this.books[34]] = "https://dcl.bibliocommons.com/item/show/1263769114";
   this.bookToDclUrl[this.books[36]] = "https://dcl.bibliocommons.com/item/show/1281023114";
   this.bookToDclUrl[this.books[39]] = "https://dcl.bibliocommons.com/item/show/1283849114";
   this.bookToDclUrl[this.books[40]] = "https://dcl.bibliocommons.com/item/show/1319530114";
   this.bookToDclUrl[this.books[42]] = "https://dcl.bibliocommons.com/item/show/1421280114";
   this.bookToDclUrl[this.books[43]] = "https://dcl.bibliocommons.com/item/show/1249360114";
   this.bookToDclUrl[this.books[45]] = "https://dcl.bibliocommons.com/item/show/1382823114";
   this.bookToDclUrl[this.books[47]] = "https://dcl.bibliocommons.com/item/show/1285427114";
   this.bookToDclUrl[this.books[48]] = "https://dcl.bibliocommons.com/item/show/1332515114";
   this.bookToDclUrl[this.books[50]] = "https://dcl.bibliocommons.com/item/show/1350467114";
   this.bookToDclUrl[this.books[51]] = "https://dcl.bibliocommons.com/item/show/1379717114";
   this.bookToDclUrl[this.books[52]] = "https://dcl.bibliocommons.com/item/show/1353525114";
   this.bookToDclUrl[this.books[53]] = "https://dcl.bibliocommons.com/item/show/1357603114";
   this.bookToDclUrl[this.books[54]] = "https://dcl.bibliocommons.com/item/show/1354400114";
   this.bookToDclUrl[this.books[56]] = "https://dcl.bibliocommons.com/item/show/1425614114";
   this.bookToDclUrl[this.books[57]] = "https://dcl.bibliocommons.com/item/show/1407440114";
   this.bookToDclUrl[this.books[58]] = "https://dcl.bibliocommons.com/item/show/1408680114";
   this.bookToDclUrl[this.books[59]] = "https://dcl.bibliocommons.com/item/show/1380027114";
   this.bookToDclUrl[this.books[60]] = "https://dcl.bibliocommons.com/item/show/1351152114";
   this.bookToDclUrl[this.books[61]] = "https://dcl.bibliocommons.com/item/show/1403137114";
   this.bookToDclUrl[this.books[62]] = "https://dcl.bibliocommons.com/item/show/1323508114";
   this.bookToDclUrl[this.books[64]] = "https://dcl.bibliocommons.com/item/show/1262334114";
   this.bookToDclUrl[this.books[65]] = "https://dcl.bibliocommons.com/item/show/1275866114";
   this.bookToDclUrl[this.books[66]] = "https://dcl.bibliocommons.com/item/show/1269118114";
   this.bookToDclUrl[this.books[68]] = "https://dcl.bibliocommons.com/item/show/1382666114";
   this.bookToDclUrl[this.books[69]] = "https://dcl.bibliocommons.com/item/show/1288127114";
   this.bookToDclUrl[this.books[70]] = "https://dcl.bibliocommons.com/item/show/1281512114";
   this.bookToDclUrl[this.books[71]] = "https://dcl.bibliocommons.com/item/show/1403896114";
   this.bookToDclUrl[this.books[72]] = "https://dcl.bibliocommons.com/item/show/1323213114";
   this.bookToDclUrl[this.books[73]] = "https://dcl.bibliocommons.com/item/show/1419962114";
   this.bookToDclUrl[this.books[74]] = "https://dcl.bibliocommons.com/item/show/1407444114";
   this.bookToDclUrl[this.books[76]] = "https://dcl.bibliocommons.com/item/show/1354705114";
   this.bookToDclUrl[this.books[77]] = "https://dcl.bibliocommons.com/item/show/1384199114";
   this.bookToDclUrl[this.books[78]] = "https://dcl.bibliocommons.com/item/show/1381429114";
   this.bookToDclUrl[this.books[79]] = "https://dcl.bibliocommons.com/item/show/1336393114";
   this.bookToDclUrl[this.books[80]] = "https://dcl.bibliocommons.com/item/show/1330611114";
   this.bookToDclUrl[this.books[81]] = "https://dcl.bibliocommons.com/item/show/1407440114";
   this.bookToDclUrl[this.books[82]] = "https://dcl.bibliocommons.com/item/show/1407440114";
   this.bookToDclUrl[this.books[84]] = "https://dcl.bibliocommons.com/item/show/1350372114";
   this.bookToDclUrl[this.books[85]] = "https://dcl.bibliocommons.com/item/show/1360810114";
   this.bookToDclUrl[this.books[86]] = "https://dcl.bibliocommons.com/item/show/1262914114";
   this.bookToDclUrl[this.books[87]] = "https://dcl.bibliocommons.com/item/show/1256448114";
   this.bookToDclUrl[this.books[88]] = "https://dcl.bibliocommons.com/item/show/1330927114";
   this.bookToDclUrl[this.books[89]] = "https://dcl.bibliocommons.com/item/show/1428882114";
   this.bookToDclUrl[this.books[90]] = "https://dcl.bibliocommons.com/item/show/1323511114";
   this.bookToDclUrl[this.books[91]] = "https://dcl.bibliocommons.com/item/show/1429640114";

   this.initializeBookToNomination();

   this.bookToNomination[this.books[0]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2017, false));
   this.bookToNomination[this.books[1]].push(new Nomination(hugo, hugo.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[2]].push(new Nomination(locus, locus.categories.properties.sf, 2017, false));
   this.bookToNomination[this.books[3]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[3]].push(new Nomination(locus, locus.categories.properties.fantasy, 2017, true));
   this.bookToNomination[this.books[3]].push(new Nomination(nebula, nebula.categories.properties.novel, 2017, true));
   this.bookToNomination[this.books[4]].push(new Nomination(nebula, nebula.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[5]].push(new Nomination(hugo, hugo.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[5]].push(new Nomination(locus, locus.categories.properties.sf, 2016, true));
   this.bookToNomination[this.books[5]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[6]].push(new Nomination(locus, locus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[7]].push(new Nomination(locus, locus.categories.properties.sf, 2016, false));
   this.bookToNomination[this.books[8]].push(new Nomination(nebula, nebula.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[9]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[10]].push(new Nomination(locus, locus.categories.properties.sf, 2017, false));
   this.bookToNomination[this.books[11]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[12]].push(new Nomination(nebula, nebula.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[13]].push(new Nomination(locus, locus.categories.properties.sf, 2016, false));
   this.bookToNomination[this.books[14]].push(new Nomination(locus, locus.categories.properties.sf, 2017, false));
   this.bookToNomination[this.books[15]].push(new Nomination(locus, locus.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[16]].push(new Nomination(locus, locus.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[17]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[17]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[18]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, false));
   this.bookToNomination[this.books[19]].push(new Nomination(hugo, hugo.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[20]].push(new Nomination(locus, locus.categories.properties.sf, 2017, false));
   this.bookToNomination[this.books[21]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[22]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, false));
   this.bookToNomination[this.books[23]].push(new Nomination(locus, locus.categories.properties.sf, 2017, true));
   this.bookToNomination[this.books[24]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[25]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2017, true));
   this.bookToNomination[this.books[26]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[27]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[28]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2017, true));
   this.bookToNomination[this.books[29]].push(new Nomination(locus, locus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[29]].push(new Nomination(nebula, nebula.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[30]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[31]].push(new Nomination(hugo, hugo.categories.properties.novel, 2016, true));
   this.bookToNomination[this.books[31]].push(new Nomination(locus, locus.categories.properties.fantasy, 2016, false));
   this.bookToNomination[this.books[31]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[32]].push(new Nomination(locus, locus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[33]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[34]].push(new Nomination(locus, locus.categories.properties.first, 2016, true));
   this.bookToNomination[this.books[34]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[35]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, false));
   this.bookToNomination[this.books[36]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, false));
   this.bookToNomination[this.books[37]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2017, false));
   this.bookToNomination[this.books[38]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[39]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2016, true));
   this.bookToNomination[this.books[39]].push(new Nomination(locus, locus.categories.properties.fantasy, 2016, false));
   this.bookToNomination[this.books[40]].push(new Nomination(locus, locus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[41]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, false));
   this.bookToNomination[this.books[42]].push(new Nomination(nebula, nebula.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[43]].push(new Nomination(locus, locus.categories.properties.fantasy, 2016, false));
   this.bookToNomination[this.books[44]].push(new Nomination(locus, locus.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[45]].push(new Nomination(locus, locus.categories.properties.sf, 2017, false));
   this.bookToNomination[this.books[46]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, false));
   this.bookToNomination[this.books[47]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[48]].push(new Nomination(locus, locus.categories.properties.sf, 2017, false));
   this.bookToNomination[this.books[49]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[50]].push(new Nomination(locus, locus.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[51]].push(new Nomination(hugo, hugo.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[52]].push(new Nomination(locus, locus.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[53]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[53]].push(new Nomination(locus, locus.categories.properties.first, 2017, true));
   this.bookToNomination[this.books[53]].push(new Nomination(nebula, nebula.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[54]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, true));
   this.bookToNomination[this.books[54]].push(new Nomination(locus, locus.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[54]].push(new Nomination(nebula, nebula.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[55]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[56]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[56]].push(new Nomination(hugo, hugo.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[57]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[58]].push(new Nomination(hugo, hugo.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[59]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, true));
   this.bookToNomination[this.books[60]].push(new Nomination(locus, locus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[61]].push(new Nomination(britishSf, britishSf.categories.properties.novel, 2018, true));
   this.bookToNomination[this.books[62]].push(new Nomination(locus, locus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[63]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2017, false));
   this.bookToNomination[this.books[64]].push(new Nomination(hugo, hugo.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[64]].push(new Nomination(locus, locus.categories.properties.sf, 2016, false));
   this.bookToNomination[this.books[65]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, false));
   this.bookToNomination[this.books[65]].push(new Nomination(locus, locus.categories.properties.first, 2016, false));
   this.bookToNomination[this.books[66]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, false));
   this.bookToNomination[this.books[67]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[68]].push(new Nomination(hugo, hugo.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[68]].push(new Nomination(nebula, nebula.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[69]].push(new Nomination(locus, locus.categories.properties.first, 2016, false));
   this.bookToNomination[this.books[70]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, false));
   this.bookToNomination[this.books[70]].push(new Nomination(locus, locus.categories.properties.first, 2016, false));
   this.bookToNomination[this.books[71]].push(new Nomination(nebula, nebula.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[72]].push(new Nomination(locus, locus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[73]].push(new Nomination(hugo, hugo.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[73]].push(new Nomination(nebula, nebula.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[74]].push(new Nomination(nebula, nebula.categories.properties.novel, 2018, false));
   this.bookToNomination[this.books[75]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[76]].push(new Nomination(locus, locus.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[77]].push(new Nomination(locus, locus.categories.properties.sf, 2017, false));
   this.bookToNomination[this.books[78]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2017, true));
   this.bookToNomination[this.books[79]].push(new Nomination(hugo, hugo.categories.properties.novel, 2017, false));
   this.bookToNomination[this.books[80]].push(new Nomination(locus, locus.categories.properties.sf, 2017, false));
   this.bookToNomination[this.books[81]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[82]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.fantasy, 2016, true));
   this.bookToNomination[this.books[82]].push(new Nomination(hugo, hugo.categories.properties.novel, 2016, false));
   this.bookToNomination[this.books[82]].push(new Nomination(locus, locus.categories.properties.fantasy, 2016, true));
   this.bookToNomination[this.books[82]].push(new Nomination(nebula, nebula.categories.properties.novel, 2016, true));
   this.bookToNomination[this.books[83]].push(new Nomination(locus, locus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[84]].push(new Nomination(locus, locus.categories.properties.sf, 2017, false));
   this.bookToNomination[this.books[85]].push(new Nomination(locus, locus.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[86]].push(new Nomination(locus, locus.categories.properties.first, 2016, false));
   this.bookToNomination[this.books[87]].push(new Nomination(locus, locus.categories.properties.sf, 2016, false));
   this.bookToNomination[this.books[88]].push(new Nomination(locus, locus.categories.properties.first, 2017, false));
   this.bookToNomination[this.books[89]].push(new Nomination(britishFantasy, britishFantasy.categories.properties.horror, 2016, false));
   this.bookToNomination[this.books[90]].push(new Nomination(locus, locus.categories.properties.fantasy, 2017, false));
   this.bookToNomination[this.books[91]].push(new Nomination(locus, locus.categories.properties.fantasy, 2016, false));

   this.initializeBookToAssessment();
   this.loadBookToAssessment();
}

SciFiInitialState.prototype.initializeBookToAssessment = function()
{
   this.bookToAssessment = UserSettings.resetBookToAssessment(this.bookToAssessment, this.books, this.bookToDclUrl, this.bookToNomination);
};

SciFiInitialState.prototype.initializeBookToNomination = function()
{
   this.books.forEach(function(book)
   {
      this.bookToNomination[book] = [];
   }, this);
};

SciFiInitialState.prototype.loadBookToAssessment = function()
{
   var myBookToAssessment = UserSettings.loadBookToAssessment();
   ObjectUtilities.merge(this.bookToAssessment, myBookToAssessment);
};

if (Object.freeze)
{
   Object.freeze(SciFiInitialState);
}

export default SciFiInitialState;