import Book from "../state/Book.js";

const SYKMBookData = [
    new Book("The Accomplice", "Steve Cavanag"),
    new Book("The Album of Dr. Moreau", "Daryl Gregory"),
    new Book("All Her Little Secrets", "Wanda M. Morris"),
    new Book("All Kinds of Ugly", "Ralph Dennis"),
    new Book("All the Devils Are Here", "Louise Penny"),
    new Book("And Now She's Gone", "Rachel Howzell Hall"),
    new Book("Angels in the Wind", "Manuel Ramos"),
    new Book("Anywhere You Run", "Wanda M. Morris"),
    new Book("The Arrangement", "M. Ravenel"),
    new Book("Arsenic and Adobo", "Mia P. Manansala"),
    new Book("Bad Actors", "Mick Herron"),
    new Book("Bad News Travels Fast", "James Swain"),
    new Book("The Bangalore Detectives Club", "Harini Nagendra"),
    new Book("Bayou Book Thief", "Ellen Byron"),
    new Book("Because I Could Not Stop for Death", "Amanda Flowe"),
    new Book("Before She Was Helen", "Caroline B. Cooney"),
    new Book("Before You Knew My Name", "Jacqueline Bublitz"),
    new Book("The Big Bundle", "Max Allan Collins"),
    new Book("Big Fat F@!k-up", "Lawrence Allan"),
    new Book("Billy Summers", "Stephen King"),
    new Book("Black Coral", "Andrew Mayne"),
    new Book("The Blackmail", "M. Ravenel"),
    new Book("Blacktop Wasteland", "S.A. Cosby"),
    new Book("Blind Vigil", "Matt Coyle"),
    new Book("Blood Sugar", "Sascha Rothchild"),
    new Book("Bloodline", "Jess Lourey"),
    new Book("Bobby March Will Live Forever", "Alan Parks"),
    new Book("The Bombay Prince", "Sujata Massey"),
    new Book("Bound", "Vanda Symon"),
    new Book("The Boy from the Woods", "Harlan Coben"),
    new Book("Brittle Karma", "Richard Helms"),
    new Book("The Bullet That Missed", "Richard Osman"),
    new Book("The Burden of Innocence", "John Nardizzi"),
    new Book("Bury Me In Shadows", "Greg Herren"),
    new Book("Cajun Kiss of Death", "Ellen Byron"),
    new Book("Canary in the Coal Mine", "Charles Salzberg"),
    new Book("Catherine House", "Elisabeth Thomas"),
    new Book("Cheddar Off Dead", "Korina Moss"),
    new Book("City on Fire", "Don Winslow"),
    new Book("Clark and Division", "Naomi Hirahara"),
    new Book("Cleopatra's Dagger", "Carole Lawrence"),
    new Book("The Collective", "Alison Gaylin"),
    new Book("The Counterfeit Wife", "Mally Becker"),
    new Book("The Damage", "Caitlin Wahrer"),
    new Book("Damaged Goods", "Debbi Mack"),
    new Book("Danger on the Atlantic", "Erica Ruth Neubauer"),
    new Book("The Dark Flood", "Deon Meyer"),
    new Book("The Dark Hours", "Michael Connelly"),
    new Book("Darkness for Light", "Emma Viskic"),
    new Book("Darling Rose Gold", "Stephanie Wrobel"),
    new Book("Dead Drop", "James L'Etoile"),
    new Book("A Dead Man's Eyes", "Lori Duffy Foster"),
    new Book("Dead Man's Leap", "Tina de Bellegarde"),
    new Book("Dead by Dawn", "Paul Doiron"),
    new Book("Dead-Bang Fall", "J.R. Sanders"),
    new Book("Death at Greenway", "Lori Rader-Day"),
    new Book("Death by Bubble Tea", "Jennifer J. Chow"),
    new Book("Death in the Aegean", "M.A. Monnin"),
    new Book("Deep State", "Chris Hauty"),
    new Book("The Deep, Deep Snow", "Brian Freeman"),
    new Book("Deer Season", "Erin Flanagan"),
    new Book("Derailed", "Mary Keliikoa"),
    new Book("Desert Star", "Michael Connelly"),
    new Book("Devil House", "John Darnielle"),
    new Book("The Devil Takes You Home", "Gabino Iglesias"),
    new Book("Devil's Chew Toy", "Rob Osler"),
    new Book("The Devil's Hand", "Jack Carr"),
    new Book("The Devil's Music", "Gabriel Valjan"),
    new Book("Dirt Creek", "Hayley Scrivenor"),
    new Book("Dirty Old Town", "Gabriel Valjan"),
    new Book("The Distant Dead", "Heather Young"),
    new Book("Djinn Patrol on the Purple Line", "Deepa Anappara"),
    new Book("Do No Harm", "Max Allan Collins"),
    new Book("Don't Know Tough", "Eli Cranor"),
    new Book("Double Agent", "Tom Bradby"),
    new Book("DoubleBlind", "Fischer Hellmann"),
    new Book("Down Range", "Taylor Moore"),
    new Book("East of Hounslow", "Khurrum Rahman"),
    new Book("Eddie's Boy", "Thomas Perry"),
    new Book("The Eighth Detective", "Alex Pavesi"),
    new Book("An Empty Grave", "Andrew Welsh-Huggins"),
    new Book("Every City is Every Other City", "John McFetridge"),
    new Book("Falling", "T.J. Newman"),
    new Book("A Familiar Stranger", "A.R. Torre"),
    new Book("Family Business", "S.J. Rozan"),
    new Book("Farewell Las Vegas", "Grant Bywaters"),
    new Book("Fatal Reunion", "Annette Dashofy"),
    new Book("The Fate of a Flapper", "Susanna Calkins"),
    new Book("The Finalist", "Joan Long"),
    new Book("The First To Lie", "Hank Phillippi Ryan"),
    new Book("Five Decembers", "James Kestrel"),
    new Book("Foote", "Tom Bredehoft"),
    new Book("Frog in a Bucket", "Clive Rosengren"),
    new Book("From Beer to Eternity", "Sherry Harris"),
    new Book("The Gallery of Beauties", "Nina Wachsman"),
    new Book("Gangland", "Chuck Hogan"),
    new Book("The Gift of the Magpie", "Donna Andrews"),
    new Book("Girl  A", "Abigail Dean"),
    new Book("Goering's Gold", "Richard O'Rawe"),
    new Book("The Goldenacre", "Philip Miller"),
    new Book("The Good Turn", "Dervla McTiernan"),
    new Book("The Goodbye Coast: A Philip Marlowe Novel", "Joe Ide"),
    new Book("Head Case", "Michael Wiley"),
    new Book("Her Name Is Knight", "Yasmin Angoe"),
    new Book("Her Perfect Life", "Hank Phillippi Ryan"),
    new Book("Hide Away", "Jason Pinter"),
    new Book("Holmes Coming", "Kenneth Johnson"),
    new Book("House on Fire", "Joseph Finder"),
    new Book("How Lucky", "Will Leitch"),
    new Book("The Hunted", "Gabriel Bergmoser"),
    new Book("Hush Hush", "Gabriel Valjan"),
    new Book("I Know Where You Sleep", "Alan Orloff"),
    new Book("In Place of Fear", "Catriona McPherson"),
    new Book("In the Blood", "Jack Carr"),
    new Book("In the Dark We Forget", "Sandra SG Wong"),
    new Book("Jackal", "Erin E. Adams"),
    new Book("Keeper", "Jessica Moor"),
    new Book("Kill All Your Darlings", "David Bell"),
    new Book("Killers of a Certain Age", "Deanna Raybourn"),
    new Book("A Lady's Guide to Mischief and Murder", "Dianne Freeman"),
    new Book("The Last Hunt", "Deon Meyer"),
    new Book("The Last Mrs. Summers", "Rhys Bowen"),
    new Book("Last Redemption", "Matt Coyle"),
    new Book("Lavender House", "Lev AC Rosen"),
    new Book("The Law of Innocence", "Michael Connelly"),
    new Book("The Lighthouse Witches", "C.J. Cooke"),
    new Book("Like a Sister", "Kellye Garrett"),
    new Book("The Lindbergh Nanny", "Mariah Fredericks"),
    new Book("Little Secrets", "Jennifer Hillier"),
    new Book("Lost Little Girl", "Gregory Stout"),
    new Book("The Lucky One", "Lori Rader-Day"),
    new Book("The Madness of Crowds", "Louise Penny"),
    new Book("The Maid", "Nita Prose"),
    new Book("Mango, Mambo, and Murder", "Raquel V. Reyes"),
    new Book("The Missing American", "Kwei Quartey"),
    new Book("Monkok Station", "Jake Needham"),
    new Book("Moonflower Murders", "Anthony Horowitz"),
    new Book("More Than You'll Ever Know", "Katie Gutierrez"),
    new Book("The Mother Next Door", "Tara Laskowski"),
    new Book("Murder Most Sweet", "Laura Jensen Walker"),
    new Book("Murder at Mallowan Hall", "Colleen Cambridge"),
    new Book("Murder at the Mena House", "Erica Ruth Neubauer"),
    new Book("Murder in Old Bombay", "Nev March"),
    new Book("Murder in the Bayou Boneyard", "Ellen Byron"),
    new Book("Murder in the Master", "Judy L. Murray"),
    new Book("The Nameless Ones", "John Connolly"),
    new Book("Never Saw Me Coming", "Vera Kurian"),
    new Book("The Ninja Betrayed", "Tori Eldridge"),
    new Book("No One Will Miss Her", "Kat Rosenfield"),
    new Book("Notes on an Execution", "Danya Kukafka"),
    new Book("On a Quiet Street", "Seraphina Nova Glass"),
    new Book("One Minute Out", "Mark Greaney"),
    new Book("Or Else", "Joe Hart"),
    new Book("The Other Black Girl", "Zakiya Dalila Harris"),
    new Book("Pay Dirt Road", "Samantha Jayne Allen"),
    new Book("Pay or Play", "Howard Michael Gould"),
    new Book("Please See Us", "Caitlin Mullen"),
    new Book("Porno Valley", "Phillip Elliot"),
    new Book("Portrait of a Thief", "Grace D. Li"),
    new Book("The Quarry Girls", "Jess Lourey"),
    new Book("Quarry's Blood", "Max Allan Collins"),
    new Book("Razorblade Tears", "S.A. Cosby"),
    new Book("Real Bad Things", "Kelly J. Ford"),
    new Book("Relentless", "Mark Greaney"),
    new Book("Remember My Face", "John Lantigua"),
    new Book("Runner", "Tracy Clark"),
    new Book("Search for Her", "Rick Mofina"),
    new Book("Secret Identity", "Alex Segura"),
    new Book("The Shape of Darkness", "Laura Purcell"),
    new Book("Shifty's Boys", " Chris Offutt"),
    new Book("Shutter", "Ramona Emerson"),
    new Book("Sierra Six", "Mark Greaney"),
    new Book("Sleeping Bear", "Connor Sullivan"),
    new Book("Slough House", "Mick Herron"),
    new Book("A Spell for Trouble", "Esme Addison"),
    new Book("Starr Sign", "C.S. O'Cinneide"),
    new Book("Steel Fear", "Brandon Webb & John David Mann"),
    new Book("Suburban Dicks", "Fabian Nicieza"),
    new Book("Symphony Road", "Gabriel Valjan"),
    new Book("Taken Too Soon", "Edith Maxwell"),
    new Book("These Toxic Things", "Rachel Howzell Hall"),
    new Book("These Women", "Ivy Pochoda"),
    new Book("The Thursday Murder Club", "Richard Osman"),
    new Book("Turn to Stone", "James W. Ziskin"),
    new Book("The Turncoat's Widow", "Mally Becker"),
    new Book("The Turning Tide", "Catriona McPherson"),
    new Book("Under a Veiled Moon", "Karen Odden"),
    new Book("Unspeakable Things", "Jess Lourey"),
    new Book("The Venice Sketchbook", "Rhys Bowen"),
    new Book("Walking Through Needles", "Heather Levy"),
    new Book("Warn Me When It's Time", "Cheryl A. Head"),
    new Book("Watch Her", "Edwin Hill"),
    new Book("We Begin at the End", "Chris Whitaker"),
    new Book("What Comes After", "JoAnne Tompkins"),
    new Book("What Meets the Eye", "Alex Kenna"),
    new Book("What You Don't See", "Tracy Clark"),
    new Book("The Wheel of Doll", "Jonathan Ames"),
    new Book("When No One Is Watching", "Alyssa Cole"),
    new Book("Who Is Maud Dixon?", "Alexandra Andrews"),
    new Book("The Wild One", "Nick Petrie"),
    new Book("Winter Counts", "David Heska Wanbli Weiden"),
    new Book("Winter Witness", "Tina deBellegarde"),
    new Book("Winter Work", "Dan Fesperman"),
    new Book("A World of Curiosities", "Louise Penny"),
];

export default SYKMBookData;
