import Book from "../state/Book.js";

const SYKMBookData = [
    new Book("The Accomplice", "Steve Cavanag"),
    new Book("The Album of Dr. Moreau", "Daryl Gregory"),
    new Book("All Her Little Secrets", "Wanda M. Morris"),
    new Book("Angels in the Wind", "Manuel Ramos"),
    new Book("The Arrangement", "M. Ravenel"),
    new Book("Arsenic and Adobo", "Mia P. Manansala"),
    new Book("Bad Actors", "Mick Herron"),
    new Book("The Bangalore Detectives Club", "Harini Nagendra"),
    new Book("Bayou Book Thief", "Ellen Byron"),
    new Book("Because I Could Not Stop for Death", "Amanda Flowe"),
    new Book("The Big Bundle", "Max Allan Collins"),
    new Book("Big Fat F@!k-up", "Lawrence Allan"),
    new Book("Billy Summers", "Stephen King"),
    new Book("Black Coral", "Andrew Mayne"),
    new Book("The Blackmail", "M. Ravenel"),
    new Book("Bobby March Will Live Forever", "Alan Parks"),
    new Book("The Bombay Prince", "Sujata Massey"),
    new Book("Bound", "Vanda Symon"),
    new Book("The Burden of Innocence", "John Nardizzi"),
    new Book("Cajun Kiss of Death", "Ellen Byron"),
    new Book("Canary in the Coal Mine", "Charles Salzberg"),
    new Book("Cheddar Off Dead", "Korina Moss"),
    new Book("City on Fire", "Don Winslow"),
    new Book("Clark and Division", "Naomi Hirahara"),
    new Book("Cleopatra's Dagger", "Carole Lawrence"),
    new Book("The Collective", "Alison Gaylin"),
    new Book("The Counterfeit Wife", "Mally Becker"),
    new Book("The Dark Flood", "Deon Meyer"),
    new Book("The Dark Hours", "Michael Connelly"),
    new Book("A Dead Man's Eyes", "Lori Duffy Foster"),
    new Book("Dead Man's Leap", "Tina de Bellegarde"),
    new Book("Dead by Dawn", "Paul Doiron"),
    new Book("Dead-Bang Fall", "J.R. Sanders"),
    new Book("Death at Greenway", "Lori Rader-Day"),
    new Book("Death by Bubble Tea", "Jennifer J. Chow"),
    new Book("Death in the Aegean", "M.A. Monnin"),
    new Book("Desert Star", "Michael Connelly"),
    new Book("Devil House", "John Darnielle"),
    new Book("The Devil Takes You Home", "Gabino Iglesias"),
    new Book("Devil's Chew Toy", "Rob Osler"),
    new Book("The Devil's Hand", "Jack Carr"),
    new Book("The Devil's Music", "Gabriel Valjan"),
    new Book("DoubleBlind", "Fischer Hellmann"),
    new Book("Down Range", "Taylor Moore"),
    new Book("An Empty Grave", "Andrew Welsh-Huggins"),
    new Book("Every City is Every Other City", "John McFetridge"),
    new Book("Falling", "T.J. Newman"),
    new Book("A Familiar Stranger", "A.R. Torre"),
    new Book("Family Business", "S.J. Rozan"),
    new Book("Fatal Reunion", "Annette Dashofy"),
    new Book("The Finalist", "Joan Long"),
    new Book("Five Decembers", "James Kestrel"),
    new Book("Foote", "Tom Bredehoft"),
    new Book("Frog in a Bucket", "Clive Rosengren"),
    new Book("The Gallery of Beauties", "Nina Wachsman"),
    new Book("Gangland", "Chuck Hogan"),
    new Book("Girl  A", "Abigail Dean"),
    new Book("Goering's Gold", "Richard O'Rawe"),
    new Book("The Goldenacre", "Philip Miller"),
    new Book("The Good Turn", "Dervla McTiernan"),
    new Book("The Goodbye Coast: A Philip Marlowe Novel", "Joe Ide"),
    new Book("Head Case", "Michael Wiley"),
    new Book("Her Name Is Knight", "Yasmin Angoe"),
    new Book("Her Perfect Life", "Hank Phillippi Ryan"),
    new Book("Holmes Coming", "Kenneth Johnson"),
    new Book("How Lucky", "Will Leitch"),
    new Book("The Hunted", "Gabriel Bergmoser"),
    new Book("Hush Hush", "Gabriel Valjan"),
    new Book("In Place of Fear", "Catriona McPherson"),
    new Book("In the Blood", "Jack Carr"),
    new Book("Kill All Your Darlings", "David Bell"),
    new Book("Killers of a Certain Age", "Deanna Raybourn"),
    new Book("Last Redemption", "Matt Coyle"),
    new Book("The Lighthouse Witches", "C.J. Cooke"),
    new Book("Like a Sister", "Kellye Garrett"),
    new Book("The Lindbergh Nanny", "Mariah Fredericks"),
    new Book("Lost Little Girl", "Gregory Stout"),
    new Book("The Madness of Crowds", "Louise Penny"),
    new Book("The Maid", "Nita Prose"),
    new Book("Mango, Mambo, and Murder", "Raquel V. Reyes"),
    new Book("Murder at Mallowan Hall", "Colleen Cambridge"),
    new Book("Murder in the Master", "Judy L. Murray"),
    new Book("The Nameless Ones", "John Connolly"),
    new Book("No One Will Miss Her", "Kat Rosenfield"),
    new Book("Notes on an Execution", "Danya Kukafka"),
    new Book("On a Quiet Street", "Seraphina Nova Glass"),
    new Book("Or Else", "Joe Hart"),
    new Book("The Other Black Girl", "Zakiya Dalila Harris"),
    new Book("Pay Dirt Road", "Samantha Jayne Allen"),
    new Book("Pay or Play", "Howard Michael Gould"),
    new Book("Porno Valley", "Phillip Elliot"),
    new Book("Quarry's Blood", "Max Allan Collins"),
    new Book("Razorblade Tears", "S.A. Cosby"),
    new Book("Relentless", "Mark Greaney"),
    new Book("Runner", "Tracy Clark"),
    new Book("Search for Her", "Rick Mofina"),
    new Book("Secret Identity", "Alex Segura"),
    new Book("The Shape of Darkness", "Laura Purcell"),
    new Book("Shifty's Boys", " Chris Offutt"),
    new Book("Sierra Six", "Mark Greaney"),
    new Book("Sleeping Bear", "Connor Sullivan"),
    new Book("Slough House", "Mick Herron"),
    new Book("Starr Sign", "C.S. O'Cinneide"),
    new Book("Steel Fear", "Brandon Webb & John David Mann"),
    new Book("Suburban Dicks", "Fabian Nicieza"),
    new Book("Symphony Road", "Gabriel Valjan"),
    new Book("These Toxic Things", "Rachel Howzell Hall"),
    new Book("The Turncoat's Widow", "Mally Becker"),
    new Book("Under a Veiled Moon", "Karen Odden"),
    new Book("The Venice Sketchbook", "Rhys Bowen"),
    new Book("Walking Through Needles", "Heather Levy"),
    new Book("Watch Her", "Edwin Hill"),
    new Book("We Begin at the End", "Chris Whitaker"),
    new Book("What Meets the Eye", "Alex Kenna"),
    new Book("The Wheel of Doll", "Jonathan Ames"),
    new Book("Who Is Maud Dixon?", "Alexandra Andrews"),
    new Book("Winter Work", "Dan Fesperman"),
    new Book("A World of Curiosities", "Louise Penny"),
];

export default SYKMBookData;
